{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-analytics",
    "version": "2026.1.070720260720",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.070720260720.aar",
          "url": "irkit-analytics-2026.1.070720260720.aar",
          "size": 325994,
          "sha512": "cf89e11d551cfbe58078d6fd4679ebe6e2b3888c24ef93cf501b9981fa8dc51ba112e9d77de46407935a3b8b02400963eb2629d5fa5622abb93cd2172e60a578",
          "sha256": "73fce2bc15cbc8bad9ad09bbe9c44f7bb86636c8a938f1fae669395d5990a5ce",
          "sha1": "1c5919284330718a973c8df39ade135f9a51d0fd",
          "md5": "8c803338c3e51955ce212311afa6fdcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-logging",
          "version": {
            "requires": "2026.1.070720260720"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.070720260720.aar",
          "url": "irkit-analytics-2026.1.070720260720.aar",
          "size": 325994,
          "sha512": "cf89e11d551cfbe58078d6fd4679ebe6e2b3888c24ef93cf501b9981fa8dc51ba112e9d77de46407935a3b8b02400963eb2629d5fa5622abb93cd2172e60a578",
          "sha256": "73fce2bc15cbc8bad9ad09bbe9c44f7bb86636c8a938f1fae669395d5990a5ce",
          "sha1": "1c5919284330718a973c8df39ade135f9a51d0fd",
          "md5": "8c803338c3e51955ce212311afa6fdcf"
        }
      ]
    }
  ]
}
