{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-analytics",
    "version": "2026.1.070520260906",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.070520260906.aar",
          "url": "irkit-analytics-2026.1.070520260906.aar",
          "size": 326012,
          "sha512": "05b628e1fffaa57a618f36096ad1f514a534fbceaadc2cd30f10f9a9e7e405e12a32670fa33a73f8b96cf509716ce922fe61f2ad5557f4c72d1edc80230a9436",
          "sha256": "c027e1a2b6f1b9fc03840d1a83eecba7c03ff2e0b6a47e4e57fc750c9f1b2130",
          "sha1": "f40657245c9b082f8436ae931e7a4893ad36c60f",
          "md5": "5f359f01f436ddf15535f766c0b61b03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-logging",
          "version": {
            "requires": "2026.1.070520260906"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.1.070520260906.aar",
          "url": "irkit-analytics-2026.1.070520260906.aar",
          "size": 326012,
          "sha512": "05b628e1fffaa57a618f36096ad1f514a534fbceaadc2cd30f10f9a9e7e405e12a32670fa33a73f8b96cf509716ce922fe61f2ad5557f4c72d1edc80230a9436",
          "sha256": "c027e1a2b6f1b9fc03840d1a83eecba7c03ff2e0b6a47e4e57fc750c9f1b2130",
          "sha1": "f40657245c9b082f8436ae931e7a4893ad36c60f",
          "md5": "5f359f01f436ddf15535f766c0b61b03"
        }
      ]
    }
  ]
}
